# Word Lite - host JVM regressions (Windows or Linux, no aapt2 and no APK needed).
# Usage:  pwsh tools/test-host.ps1 [-RealDocx <path>] [-SkipRealDoc]
param(
    [string]$RealDocx = "",
    [switch]$SkipRealDoc
)
$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
Set-Location $root

$classes = Join-Path $root "artifacts/build/host-classes"
$gen     = Join-Path $root "artifacts/build/host-gen"
$tests   = Join-Path $root "artifacts/build/host-test-classes"
$out     = Join-Path $root "artifacts/tests/host"
$report  = Join-Path $root "reports/current"
foreach ($dir in @($classes, $tests, $out, $report, (Join-Path $out "roundtrip"))) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
Remove-Item -Recurse -Force (Join-Path $classes "*"), (Join-Path $tests "*") -ErrorAction SilentlyContinue

# The shipping R class comes from aapt2; the host compile only needs the ids the app touches.
$rdir = Join-Path $gen "com/rikkahub/wordlite"
New-Item -ItemType Directory -Force -Path $rdir | Out-Null
$stub = @(
    "package com.rikkahub.wordlite;",
    "/** Host compile stub; the shipping R class is generated by aapt2. */",
    "public final class R {",
    "    public static final class drawable { public static final int ic_file = 1; public static final int ic_hero = 2; }",
    "    public static final class layout { public static final int simple_spinner_dropdown_item = 3; }",
    "}"
)
Set-Content -Encoding utf8NoBOM -Path (Join-Path $rdir "R.java") -Value $stub

$android = Join-Path $root "tools/android-35.jar"
$appFiles = @(Get-ChildItem -Recurse -File -Filter *.java (Join-Path $root "app/src/main/java") | ForEach-Object { $_.FullName })
$appFiles += (Join-Path $rdir "R.java")
$listing = Join-Path ([System.IO.Path]::GetTempPath()) ("wordlite-app-" + [Guid]::NewGuid().ToString("N") + ".txt")
Set-Content -Encoding ascii -Path $listing -Value $appFiles
Write-Host ("== javac app ({0} files) ==" -f $appFiles.Count)
& javac -nowarn -encoding UTF-8 -classpath $android -d $classes "@$listing"
$code = $LASTEXITCODE
Remove-Item $listing -ErrorAction SilentlyContinue
if ($code -ne 0) { throw "app compile failed" }

$testFiles = @(Get-ChildItem -File -Filter *.java (Join-Path $root "tests") | ForEach-Object { $_.FullName })
Write-Host ("== javac tests ({0} files) ==" -f $testFiles.Count)
& javac -nowarn --add-modules jdk.httpserver -encoding UTF-8 -classpath "$classes;$android" -d $tests $testFiles
if ($LASTEXITCODE -ne 0) { throw "test compile failed" }

$cp = "$tests;$classes;$android"
$suites = New-Object System.Collections.ArrayList
function Add-Suite([string]$name, $argv) { [void]$suites.Add([pscustomobject]@{ Name = $name; Args = $argv }) }
Add-Suite "Regression"             @("tests/fixture.docx", "$out/roundtrip")
Add-Suite "ScriptRegression"       @()
Add-Suite "WordLineHeightRegression" @()
Add-Suite "TextCorpusRegression"   @()
Add-Suite "SourceLedgerRegression" @()
Add-Suite "CharLedgerRegression"   @()
Add-Suite "SharedSpanRegression" @()
Add-Suite "CandidateRankerRegression" @()
Add-Suite "HitMapRegression" @()
Add-Suite "RoutesRegression"      @()
Add-Suite "CorpusImportRegression" @()
Add-Suite "RewriteRobustnessRegression" @("tests/corpus/real-prose.txt")
Add-Suite "AigcRegression"         @()
# 逐特征方向审计（带标注语料）。缺语料一律判失败，不许静默跳过；它同时是"未标定就不许给数"的闸门。
Add-Suite "AigcFeatureAuditRegression" @()
# 离线 n-gram 模型（训练台 tools/build-aigc-model.py 导出的 assets/aigc/*）：装载、两侧口径一致、
# 真稿独立留出、出厂闸门。缺权重文件或缺标注语料一律判失败；这一版 AUC 不达标，闸门必须仍然是关的。
Add-Suite "AigcOfflineModelRegression" @("app/src/main/assets/aigc", "tests/corpus")
Add-Suite "LocalRewriteRegression" @()
Add-Suite "DeepModeAudit"          @("tests/corpus/real-prose.txt", "tests/corpus/oa-planted-cjmenet.txt")
Add-Suite "RewriteRateRegression"  @("tests/samples/input-liu.docx", "tests/corpus/oa-planted-cjmenet.txt", "$out/rewrite-rate")
Add-Suite "DetectRegression"       @()
Add-Suite "RetrievalCoverageRegression" @()
Add-Suite "WanfangPagingRegression"    @()
Add-Suite "CnkiSearchRegression"   @()

Add-Suite "CnkiTouchRegression"    @()
Add-Suite "CqvipStateRegression"   @()
Add-Suite "PreservationRegression" @("tests/samples/complex-preservation.docx")
Add-Suite "ReviewRegression"       @("tests/fixture.docx", "$out/threaded-revisions.docx")
Add-Suite "PdfRegression"          @("$out/metadata.pdf")
Add-Suite "ApiRegression"          @()
Add-Suite "ReportStoreRegression"  @()
Add-Suite "ZeroRateAudit"          @("tests/samples/input-liu.docx", "tests/corpus/real-prose.txt", "tests/corpus/aigc-cartoon.txt")
# 判据没有死的证据（与 ZeroRateAudit 互补）：语料里确实有可比材料时，抄进去的那一段不许印成 0.00%。缺语料一律 throw，不静默跳过。
Add-Suite "DetectionFloor"       @("tests/corpus", "$out/detection-floor-library")
# 摘要层（近似）的量台与闸门：阈值两堆分布 + 负对照 + 不与正文级同账 + 每次请求留档（A4）。全程离线。
Add-Suite "AbstractLayerRegression" @("tests/corpus")
# 字体替代表的账：标题写着华文新魏的稿子不许再悄悄变宋体，替代是谁、缺了哪些字，都要说得出。
Add-Suite "FontSubstitution"      @("tests/samples/input-liu.docx")
if (-not $SkipRealDoc) {
    $doc = if ($RealDocx) { $RealDocx } else { Join-Path $root "tests/samples/input-liu.docx" }
    if (Test-Path $doc) {
        Add-Suite "OriginalDocxRegression" @($doc, "$out/original-roundtrip.docx")
        Add-Suite "TableGeometryRegression" @($doc, "$out/table-geometry.docx", (Join-Path $root "tests/fixture.docx"))
    }
}

$failed = 0
foreach ($suite in $suites) {
    $class = "com.rikkahub.wordlite." + $suite.Name
    $log = Join-Path $report ($suite.Name.ToLower() + ".log")
    $argv = @("--add-modules", "jdk.httpserver", "-classpath", $cp, $class) + @($suite.Args)
    & java @argv *> $log
    $code = $LASTEXITCODE
    $tail = if (Test-Path $log) { (Get-Content $log | Where-Object { $_ -ne "" } | Select-Object -Last 1) } else { "" }
    if ($code -eq 0) { Write-Host ("PASS {0,-24} {1}" -f $suite.Name, $tail) }
    else { $failed++; Write-Host ("FAIL {0,-24} exit {1} (see {2})" -f $suite.Name, $code, $log) -ForegroundColor Red }
}
Write-Host "note: FontAssetsRegression needs the built APK; use sh tools/build.sh then sh tools/test.sh"
if ($failed -gt 0) { throw "$failed suite(s) failed" }
Write-Host "all host JVM suites passed"

